<html>
<head>
  <title>ReadAFile - Your Personal File Reader</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
  <div class="container">
    <h1>ReadAFile - Your Personal File Reader</h1>
    <p>Upload any type of file and start reading it in a matter of seconds!</p>
    <form>
      <div class="mb-3">
        <label for="fileInput" class="form-label">Select a file</label>
        <input type="file" class="form-control" id="fileInput">
      </div>
      <div class="form-check mb-3">
        <input class="form-check-input" type="checkbox" id="ignorePreviousInput">
        <label class="form-check-label" for="ignorePreviousInput">
          Ignore all previous input
        </label>
      </div>
      <button type="submit" class="btn btn-primary">Read File</button>
    </form>
    <div class="d-none" id="loadingIndicator">
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
    <div class="mt-3" id="fileContent"></div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
  <script>
    const form = document.querySelector('form');
    const fileInput = document.querySelector('#fileInput');
    const ignorePreviousInput = document.querySelector('#ignorePreviousInput');
    const loadingIndicator = document.querySelector('#loadingIndicator');
    const fileContent = document.querySelector('#fileContent');

    form.addEventListener('submit', (event) => {
      event.preventDefault();
      fileContent.innerHTML = '';
      loadingIndicator.classList.remove('d-none');
      const formData = new FormData();
      formData.append('file', fileInput.files[0]);
      formData.append('ignorePreviousInput', ignorePreviousInput.checked);
      fetch('/read-file', {
        method: 'POST',
        body: formData
      })
      .then(response => response.text())
      .then(text => fileContent.innerHTML = text)
      .finally(() => loadingIndicator.classList.add('d-none'));
    });
  </script>
</body>
</html>
